{% set name = 'bob.bio.video' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.image
    - bob.io.video
    - bob.learn.activation
    - bob.math
    - bob.sp
    - bob.ip.base
    - bob.ip.color
    - bob.ip.draw
    - bob.ip.gabor
    - bob.learn.linear
    - bob.learn.em
    - bob.measure
    - bob.db.base
    - bob.bio.base
    - bob.bio.face
    - bob.learn.boosting
    - bob.ip.facedetect
    - bob.ip.flandmark
  run:
    - python
    - setuptools

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - bob.db.atnt
    - bob.db.mobio
    - bob.db.youtube
    - gridtk

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD License
  summary: Run biometric recognition algorithms on videos
  license_family: BSD
